INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (1, 'Medication Reminders', 'care_medication.png', '', 0, 1, '2016-08-17 12:17:35');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (2, 'Staying Active', 'care_active.png', '', 1, 1, '2016-08-17 12:22:10');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (3, 'Meal Preparatioon & Grocery', 'care_meal.png', '', 2, 1, '2016-08-17 12:22:18');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (4, 'Escort Services', 'care_escort.png', '', 3, 1, '2016-08-17 12:22:33');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (5, 'Housekeeping', 'care_house.png', '', 4, 1, '2016-08-17 12:22:44');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (6, 'Personal Care & Hygiene', 'care_personal.png', '', 5, 1, '2016-08-17 12:22:54');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (7, 'Companionship', 'care_companion.png', '', 6, 1, '2016-08-17 12:23:09');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (8, 'Check-in Visit', 'care_visit.png', '', 7, 1, '2016-08-17 12:23:16');
INSERT INTO `service` (`id`, `service`, `icon`, `description`, `order`, `is_active`, `last_updated`) VALUES (9, 'Night Survelliance', 'care_surveillance.png', '', 8, 1, '2016-08-17 12:23:22');


INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (1, 1, 'Serve Medicatioons', '', '', 0, 1, '2016-08-17 12:23:52');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (2, 1, 'Medication Reminders', '', '', 0, 1, '2016-08-17 12:24:02');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (3, 2, 'Simple Exercises', '', '', 0, 1, '2016-08-17 12:24:30');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (4, 2, 'Manual Transfers', '', '', 0, 1, '2016-08-17 12:24:33');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (5, 2, 'Familiar with walking aids', '', '', 0, 1, '2016-08-17 12:24:42');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (6, 2, 'Familiar with func?ons of wheelchair', '', '', 0, 1, '2016-08-17 12:24:58');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (7, 3, 'Meal Preparation', '', '', 0, 1, '2016-08-17 12:25:10');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (8, 3, 'Grocery Shopping', '', '', 0, 1, '2016-08-17 12:25:32');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (9, 4, 'Valid driving licence', '', '', 0, 1, '2016-08-17 12:25:42');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (10, 4, 'Own Car', '', '', 0, 1, '2016-08-17 12:25:53');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (11, 4, 'Confident to Drive', '', '', 0, 1, '2016-08-17 12:26:05');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (12, 4, 'Manual Transfers', '', '', 0, 1, '2016-08-17 12:26:39');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (13, 4, 'Familiar with walking aids', '', '', 0, 1, '2016-08-17 12:27:00');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (14, 4, 'Familiar with functions of wheelchair', '', '', 0, 1, '2016-08-17 12:27:11');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (15, 5, 'Bed making', '', '', 0, 1, '2016-08-17 12:27:36');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (16, 5, 'Room cleaning', '', '', 0, 1, '2016-08-17 12:27:49');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (17, 5, 'Laundry', '', '', 0, 1, '2016-08-17 12:28:01');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (18, 5, 'Floor sweeping', '', '', 0, 1, '2016-08-17 12:28:26');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (19, 5, 'Floor Vacuum', '', '', 0, 1, '2016-08-17 12:28:40');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (20, 5, 'Floor Mopping', '', '', 0, 1, '2016-08-17 12:28:52');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (21, 6, 'Bed Bath', '', '', 0, 1, '2016-08-17 12:29:05');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (22, 6, 'Showering', '', '', 0, 1, '2016-08-17 12:29:25');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (23, 6, 'Change Diaper', '', '', 0, 1, '2016-08-17 12:29:36');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (24, 6, 'Manual Transfers', '', '', 0, 1, '2016-08-17 12:29:48');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (25, 7, 'Chitchat', '', '', 0, 1, '2016-08-17 12:30:01');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (26, 7, 'Play Games', '', '', 0, 1, '2016-08-17 12:30:15');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (27, 8, 'Check-in Visit', '', '', 0, 1, '2016-08-17 12:30:38');
INSERT INTO `skill` (`id`, `service_id`, `skill`, `description`, `sub_description`, `order`, `is_active`, `last_updated`) VALUES (28, 9, 'Night Survelliance', '', '', 0, 1, '2016-08-17 12:30:44');
